clusterstats/blueprint_api.py
import copy
import os
import time

import flask

from clusterstats import swarm
from clusterstats import utils
from clusterstats import version

blueprint = flask.Blueprint('api',  __name__)

version = {
    'version': version.software_version,
    'build': os.getenv('BUILD', 'unknown'),
    'updates': {'services': None, 'nodes': None, 'containers': None}
}


# ----------------------------------------------------------------------
# VERSION API IMPLEMENTATION
# ----------------------------------------------------------------------

@blueprint.route('/version')
@utils.requires_user("admin", "viewer")
def api_version():
    global version
    version['updates'] = swarm.instance.updates
    return flask.jsonify(version)


# ----------------------------------------------------------------------
# SWARM API IMPLEMENTATION
# ----------------------------------------------------------------------

@blueprint.route('/swarm')
@utils.requires_user("admin", "viewer")
def api_swarm():
    if flask.request.args.get('full'):
        return flask.jsonify(swarm.instance.swarm)
    else:
        result = copy.deepcopy(swarm.instance.swarm)
        result['containers'] = len(result['containers'])
        result['services'] = len(result['services'])
        result['nodes'] = len(result['nodes']['active'])
        return flask.jsonify(result)


@blueprint.route('/swarm/stats', defaults={'period': None})
@blueprint.route('/swarm/stats/<period>')
@utils.requires_user("admin", "viewer")
def api_swarm_stats(period):
    return get_stats('swarm', period)


# ----------------------------------------------------------------------
# NODES API IMPLEMENTATION
# ----------------------------------------------------------------------

@blueprint.route('/nodes', defaults={'node': None})
@blueprint.route('/nodes/<node>')
@utils.requires_user("admin", "viewer")
def api_nodes(node):
    if node:
        (_, v) = utils.find_item(swarm.instance.nodes, node)
        if v:
            return flask.jsonify(v)
        else:
            return flask.Response('node "%s" not found' % node, status=404)
    else:
        if flask.request.args.get('full'):
            return flask.jsonify(swarm.instance.nodes)
        else:
            result = {k: v['name'] for k, v in swarm.instance.nodes.items()}
            return flask.jsonify(result)


@blueprint.route('/nodes/<node>/stats', defaults={'period': None})
@blueprint.route('/nodes/<node>/stats/<period>')
@utils.requires_user("admin", "viewer")
def api_nodes_stats(node, period):
    (k, _) = utils.find_item(swarm.instance.nodes, node)
    if k:
        return get_stats(k, period)
    else:
        return flask.Response('node "%s" not found' % node, status=404)


# ----------------------------------------------------------------------
# SERVICES API IMPLEMENTATION
# ----------------------------------------------------------------------

@blueprint.route('/services', defaults={'service': None})
@blueprint.route('/services/<service>')
@utils.requires_user("admin", "viewer")
def api_services(service=None):
    if service:
        (_, v) = utils.find_item(swarm.instance.services, service)
        if v:
            if flask.request.authorization.username == 'admin':
                return flask.jsonify(v)
            else:
                v = copy.copy(v)
                v.pop('env', None)
                return flask.jsonify(v)
        else:
            return flask.Response('service "%s" not found' % service, status=404)
    else:
        if flask.request.args.get('full'):
            if flask.request.authorization.username == 'admin':
                return flask.jsonify(swarm.instance.services)
            else:
                results = dict()
                for k, v in swarm.instance.services.items():
                    results[k] = copy.copy(v)
                    results[k].pop('env', None)
                return flask.jsonify(results)
        else:
            results = {k: v['name'] for k, v in swarm.instance.services.items()}
            return flask.jsonify(results)


@blueprint.route('/services', methods=['POST'])
@utils.requires_user("admin")
def api_services_create():
    data = flask.request.get_json(force=True)
    if data:
        (status, msg) = swarm.instance.service_create(**data)
        if status:
            return flask.Response('service created: %s image=%s id=%s' % (data['name'], data['image'], msg))
        else:
            return flask.Response('could not create service: %s' % msg, status=400)
    else:
        return flask.Response('invalid data posted, expected JSON', status=400)


@blueprint.route('/services/<service>', methods=['DELETE'])
@utils.requires_user("admin")
def api_services_remove(service):
    response = swarm.instance.service_remove(service)
    return flask.Response(response, mimetype='text/ascii')


@blueprint.route('/services/<service>/logs')
@utils.requires_user("admin", "viewer")
def api_services_logs(service):
    lines = int(flask.request.args.get('lines', '20'))
    if lines == 0:
        lines = 'all'
    log = swarm.instance.service_log(service, lines=lines)
    if log is not None:
        return flask.Response(log, mimetype='text/ascii')
    else:
        return flask.Response('No logs found for %s' % service, status=404)


@blueprint.route('/services/<service>/restart', methods=['POST'])
@utils.requires_user("admin")
def api_services_restart(service):
    (k, v) = utils.find_item(swarm.instance.services, service)
    if k and v:
        replicas = v['replicas']['requested']
        api_services_scale(k, 0)
        time.sleep(30)
        api_services_scale(k, replicas)
        return flask.Response('service %s restarted' % service)
    else:
        return flask.Response('service "%s" not found' % service, status=404)


@blueprint.route('/services/<service>/stop', methods=['POST'])
@utils.requires_user("admin")
def api_services_stop(service):
    (k, _) = utils.find_item(swarm.instance.services, service)
    if k:
        swarm.instance.service_stop(k)
        return flask.Response('service %s stopped' % service)
    else:
        return flask.Response('service "%s" not found' % service, status=404)


@blueprint.route('/services/<service>/update', methods=['POST'])
@utils.requires_user("admin")
def api_services_update(service):
    (k, _) = utils.find_item(swarm.instance.services, service)
    if k:
        swarm.instance.service_update(k)
        return flask.Response('service %s restarted' % service)
    else:
        return flask.Response('service "%s" not found' % service, status=404)


@blueprint.route('/services/<service>/scale/<count>', methods=['PUT'])
@utils.requires_user("admin")
def api_services_scale(service, count):
    (status, msg) = swarm.instance.service_scale(service, count)
    if status:
        return flask.Response('', status=204)
    else:
        return flask.Response(msg, status=400)


@blueprint.route('/services/<service>/stats', defaults={'period': None})
@blueprint.route('/services/<service>/stats/<period>')
@utils.requires_user("admin", "viewer")
def api_services_stats(service, period):
    (k, _) = utils.find_item(swarm.instance.services, service)
    if k:
        return get_stats(k, period)
    else:
        return flask.Response('service "%s" not found' % service, status=404)


# ----------------------------------------------------------------------
# CONTAINERS API IMPLEMENTATION
# ----------------------------------------------------------------------

@blueprint.route('/containers', defaults={'container': None})
@blueprint.route('/containers/<container>')
@utils.requires_user("admin", "viewer")
def api_containers(container=None):
    if container:
        (_, v) = utils.find_item(swarm.instance.containers, container)
        if v:
            if flask.request.authorization.username == 'admin':
                return flask.jsonify(v)
            else:
                v = copy.copy(v)
                v.pop('env', None)
                return flask.jsonify(v)
        else:
            return flask.Response('container "%s" not found' % container, status=404)
    else:
        if flask.request.args.get('full'):
            if flask.request.authorization.username == 'admin':
                return flask.jsonify(swarm.instance.containers)
            else:
                results = dict()
                for k, v in swarm.instance.containers.items():
                    results[k] = copy.copy(v)
                    results[k].pop('env', None)
                return flask.jsonify(results)
        else:
            results = {k: v['name'] for k, v in swarm.instance.containers.items()}
            return flask.jsonify(results)


@blueprint.route('/containers/<container>/logs')
@utils.requires_user("admin", "viewer")
def api_containers_logs(container):
    lines = int(flask.request.args.get('lines', '20'))
    if lines == 0:
        lines = 'all'
    log = swarm.instance.container_log(container, lines=lines)
    if log is not None:
        return flask.Response(log, mimetype='text/ascii')
    else:
        return flask.Response('No logs found for %s' % container, status=404)


@blueprint.route('/containers/<container>/stats', defaults={'period': None})
@blueprint.route('/containers/<container>/stats/<period>')
@utils.requires_user("admin", "viewer")
def api_containers_stats(container, period):
    (k, _) = utils.find_item(swarm.instance.containers, container)
    if k:
        return get_stats(k, period)
    else:
        return flask.Response('container "%s" not found' % container, status=404)


# ----------------------------------------------------------------------
# LOG COLLECTOR
# ----------------------------------------------------------------------

def get_stats(what, period):
    """
    From the stats return the stats for the right period. If no period is given it will retunr
    a list of the periods.
    :param what: the stats to return, swar, container id, service id, etc.

clusterstats/blueprint_html.py
import flask

from clusterstats import swarm
from clusterstats import utils

blueprint = flask.Blueprint('html',  __name__, static_folder='static', template_folder='templates')


@blueprint.route('/', defaults={'page': 'dashboard'})
@blueprint.route('/<page>')
@utils.requires_user("admin", "viewer")
def html_page(page):
    """
    Return any static page with .html appended.
    """
    return blueprint.send_static_file('%s.html' % page)


@blueprint.route('/services/<service>/logs')
@utils.requires_user("admin", "viewer")
def html_services_logs(service):
    """
    Return log viewer for a specific service.
    """
    (k, v) = utils.find_item(swarm.instance.services, service)
    return flask.render_template('logs.html', service_id=k, service_name=v['name'], containers=v['containers'])


@blueprint.route('/swagger')
def html_swagger():
    """
    Return swagger documentation
    """
    return blueprint.send_static_file('swagger.yml')

clusterstats/templates/logs.html
<!DOCTYPE html>
<html>
<head>
  <title>Swarm Statistics Logs</title>
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lib/css/bootstrap.min.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lib/css/keen-dashboards.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lib/css/dc.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom.css') }}">
</head>
<body class="application">

  <!-- menu bar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#swarm-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Swarm Dashboard</a>
      </div>
      <div class="collapse navbar-collapse" id="swarm-navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('html.html_page', page='dashboard') }}">Dashboard</a></li>
          <li><a href="{{ url_for('html.html_page', page='nodes') }}">Nodes</a></li>
          <li><a href="{{ url_for('html.html_page', page='services') }}">Services</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- menu bar -->

  <div class="container-fluid">

    <h3>Service Logs : {{ service_name }}</h3>

    <div class="row">
      <div class="col-sm-12">
        <div class="chart-wrapper">
          <div class="chart-title">
            Cores
            <small class="pull-right">
              <label class="pull-left" style="margin-right: 10px;">
                Time Period:
                <select id="log-lines">
                  <option value="20" selected>Last 20 lines</option>
                  <option value="50">Last 50 lines</option>
                  <option value="100">Last 100 lines</option>
                  <option value="0">Full log</option>
                </select>
              </label>
              <label class="pull-left" style="margin-right: 10px;">
                Container:
                <select id="log-container">
                  <option value="all" selected>All Containers</option>
                  {% for c in containers %}
                  <option value="{{ c.id }}">{{ c.id }}</option>
                  {% endfor %}
                </select>
              </label>
            </small>
          </div>
          <div class="chart-stage" id="logs-stage">
              <pre><div id="logs"></div></pre>
          </div>
          <div class="chart-notes" id="logs-notes">
            Notes about this chart
          </div>
        </div>
      </div>
    </div>

    <hr>

    <p class="small text-muted">
      <span style="float: left">Created as part of <a href="https://browndog.ncsa.illinois.edu">Brown Dog</a></span>
      <span style="float: right">Layout and style by <a href="https://keen.io">Keen IO</a></span>
    </p>

  </div>

  <script type="text/javascript" src="{{ url_for('html.static', filename='lib/js/jquery.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('html.static', filename='lib/js/bootstrap.min.js') }}"></script>
  <script type="text/javascript">
    function showLogs() {
      if ($("#log-container").val() == "all") {
        var url = "{{ url_for('api.api_services_logs', service=service_id) }}?lines=" + $("#log-lines").val();
        console.log(url);
        $.get(url, function(data) {
          $('#logs').text(data);
          setTimeout(showLogs, 30 * 1000);
        });
      } else {
        var url = "{{ url_for('api.api_containers_logs', container='--') }}?lines=" + $("#log-lines").val();
        url = url.replace("--", $("#log-container").val());
        console.log(url);
        $.get(url, function(data) {
          $('#logs').text(data);
          setTimeout(showLogs, 30 * 1000);
        });
      }
    }

    $("#log-lines").change(showLogs);
    $("#log-container").change(showLogs);
    $(window).load(showLogs);
  </script>
</body>
</html>